# Section-Alignment-tool-Revit
    It's used to create the section alignment line parallel to selected elements like wall, pipe, duct, etc...



#Section alignment line tool parallel to the elements Revit

Objective:
    It's used to create the section alignment line parallel to selected elements like wall,pipe,duct,etc...

Procedures:
  
Script setup:
     
     1) Install pyrevit

     2) Go to PyRevitExtension folder

     3) Create .extension folder

     3) create .tab folder inside .extension  folder

     4) Set .panel and _layout setup

     5) Crate .pushbutten folder inside the Tab

     6) Set icon file and Script file


 In revit user Interface:

      1) Create the elemnt and selected

      2) Click the pushbutton were you created on top of the Interface

      3) Now the section line will be created parallel to the elemnt

  

